### ISSUE TITLE
Jetty listening on 0.0.0.0:3003

### ISSUE THREAD

**Issue by shantycode** [ananas-analytics/ananas-desktop#70]
Hey folks,

it just occurred to me that ananas is running a Jetty 9.3 (jetty-9.3.z-SNAPSHOT) on Port 3003 listening on 0.0.0.0 on linux. I can not say if this version is potentially vulnerable to CVE 2016-4800 (https://www.cvedetails.com/cve/CVE-2016-4800/) but there are updates available. I would also suggest listening on localhost only if not explicitly defined by a user.

By the way, the "Get Started" link in your wiki (https://github.com/ananas-analytics/ananas-desktop/wiki) points to `http://localhost:3000/docs/user-guide/getting-started`.

Cheers
Florian

**Comment by bhou** [comment]
@shantycode Thanks for your report! Ananas Desktop uses a Sparkjava server as backend, you can run this server from CLI directly. It is intended to listen on localhost only when running with the UI. For the potentially vulnerable you mentioned, it is because we used an old version of Sparkjava, which depends on jetty 9.3.

I create a fix to 
- upgrade sparkjava server to the latest version 2.9.1 https://mvnrepository.com/artifact/com.sparkjava/spark-core/2.9.1, which depends on jetty server 9.4.18.v20190429 
- Explicitly listen to "localhost" only for ananas server

Fix commit here:  https://github.com/ananas-analytics/ananas-desktop/commit/a9e844dfe8a32c58da7b7d3627f995fbd9088cf9

**Comment by bhou** [comment]
fix in PR: https://github.com/ananas-analytics/ananas-desktop/pull/75
